"""empty message

Revision ID: 290c95052707
Revises: cdfbcd7ac84e
Create Date: 2020-04-01 14:25:59.618725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290c95052707'
down_revision = 'cdfbcd7ac84e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_name', sa.String(), nullable=True))
    op.add_column('shows', sa.Column('venue_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'venue_name')
    op.drop_column('shows', 'artist_name')
    # ### end Alembic commands ###
